projet/app/urls.py
from django.urls import path
from . import views  

urlpatterns = [
    #Home Page
    path('', views.index, name='index'),
    path('magasin',views.magasin, name='magasin'),
    path('centres',views.centres, name='centres'),
    path('tableauxDeBord',views.tableauxDeBord, name='TableauxDeBord'),


    #Magasin Section
    #Client
    path('client',views.afficher_clients,name='liste_clients'),
    path('client/ajouter',views.ajouter_client, name="addCl"),
    path('client/edit/<int:pk>',views.modifier_client, name="editCl"),
    path('client/delete/<int:pk>',views.supprimer_client, name="deleteCl"),
    #Fournisseur
    path('fournisseur',views.afficher_fournisseurs,name='liste_fournisseurs'),
    path('fournisseur/ajouter',views.ajouter_fournisseur, name="addF"),
    path('fournisseur/edit/<int:pk>',views.modifier_fournisseur, name="editF"),
    path('fournisseur/delete/<int:pk>',views.supprimer_fournisseur, name="deleteF"),
    #Employe
    path('employe',views.afficher_employes,name='liste_employes'),
    path('employe/ajouter',views.ajouter_employe, name="addE"),
    path('employe/edit/<int:pk>',views.modifier_employe, name="editE"),
    path('employe/delete/<int:pk>',views.supprimer_employe, name="deleteE"),
    #Produit
    path('produit',views.afficher_produits,name='liste_produits'),
    path('produit/ajouter',views.ajouter_produit, name="addPrd"),
    path('produit/edit/<int:pk>',views.modifier_produit, name="editPrd"),
    path('produit/delete/<int:pk>',views.supprimer_produit, name="deletePrd"),
    #Centre
    path('centre',views.afficher_centres,name='liste_centres'),
   
    #Matiere Premiere
    path('matierePremiere',views.afficher_matierePremieres,name='liste_matierePremieres'),
    path('matierePremiere/edit/<int:pk>/',views.modifier_matierePremiere, name="editMP"),
    path('matierePremiere/delete/<int:pk>',views.supprimer_matierePremiere, name="deleteMP"),
    path('matierePremiere/ajouter',views.ajouter_matierePremiere, name="addMPr"),
    #Achat Matiere Premiere
    path('AchatMatierePremiere',views.Achat_matierePremiere, name="addMP"),
    path('JournalAchatMatierePremiere',views.afficher_JournalAchatMP,name="liste_AchatmatierePremieres"),
    path('JournalAchatMatierePremiere/edit/<int:pk>/',views.modifier_AchatmatierePremiere, name="editAchatMP"),
    path('JournalAchatMatierePremiere/delete/<int:pk>',views.supprimer_AchatmatierePremiere, name="deleteAchatMP"),
    path('ReglementFournisseur',views.ReglementAchat_matierePremiere,name="ReglerAchatMP"),
    path('get_solde/', views.get_solde, name='get_solde'),
    
    #Transfert Matiere Premiere
    path('TransfertMatierePremiere',views.Transfert_matierePremiere, name="TransMP"),
    path('JournalTransfertMatierePremiere',views.afficher_JournalTransfertMP, name="liste_TransfertmatierePremieres"),
    
    #Vente Matiere Premiere
    path('VenteMatierePremiere',views.Vente_MatierePremiere, name="VenteMP"),
    path('JournalVenteMatierePremiere',views.afficher_JournalVenteMP, name="liste_VentematierePremieres"),
    path('JournalVenteMatierePremiere/edit/<int:pk>/',views.modifier_VentematierePremiere, name="editVenteMP"),
    path('JournalVenteMatierePremiere/delete/<int:pk>',views.supprimer_VentematierePremiere, name="deleteVenteMP"),
    path('PaiementCredit',views.PaiementCredit_matierePremiere,name="PaiementCredMP"),
    path('get_credit/', views.get_credit, name='get_credit'),
    
    #Etat De Stock
    path('EtatDeStock',views.afficher_etatStock, name="EtatStock"),

    #Centre Section
    path('sectionCentre/<int:centre_id>',views.section_centre,name="section_centre"),
    #Activités du Centre
    path('activitesCentre/<int:centre_id>',views.activites_centre,name="activites_centre"),
    #Journal des Transferts
    path('journalTransfert/<int:centre_id>',views.journal_transfert,name="journal_transfert"),
    #Ventes des Produits
    path('journalVente/<int:centre_id>',views.journal_vente,name="journal_vente"),
    path('journalVente/ajouter/<int:centre_id>',views.ajouter_vente,name="addVente"),
    #Paiement Crédit Client
    path('paiementCredit/<int:centre_id>',views.paiement_credit,name="paiement_credit"),

    #Module Employé
    path('moduleEmploye/<int:centre_id>',views.module_employe,name="module_employe"),
    path('modifierPoints/<int:pk>',views.modifier_points,name="editPts"),

    path('absence/<int:pk>',views.afficher_absence,name="absence"),
    path('absence/ajouter/<int:employe_id>',views.ajouter_absence,name="addAbsence"),
    path('absence/edit/<int:pk>',views.modifier_absence,name="editAbsence"),
    path('absence/delete/<int:pk>',views.supprimer_absence,name="deleteAbsence"),

    path('avanceSalaire/<int:pk>',views.afficher_avanceSalaire,name="avanceSalaire"),
    path('avanceSalaire/ajouter/<int:employe_id>',views.ajouter_avanceSalaire,name="addAvanceSalaire"),
    path('avanceSalaire/edit/<int:pk>',views.modifier_avanceSalaire,name="editavanceSalaire"),
    path('avanceSalaire/delete/<int:pk>',views.supprimer_avanceSalaire,name="deleteavanceSalaire"),


    #Tableux de Bord Section
    path('analyseVente',views.analyse_vente,name="analyse_vente"),
    path('tableauxDeBord/<int:centre_id>',views.afficher_tableaux,name="tableaux_de_bord"),
    path('tableauxDeBordachat',views.afficher_tableaux_achat,name="tableaux_de_bordach"),
]

projet/projet/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path("select2/", include("django_select2.urls")),
]

projet/app/models.py
from django.db import models
from datetime import datetime
import calculation



class client(models.Model):
    # codeCl=models.AutoField(primary_key=True)
    nomCl=models.CharField(max_length=50)
    prenomCl=models.CharField(max_length=50)
    adresseCl=models.CharField(max_length=50)
    telephoneCl=models.CharField(max_length=10)
    credit=models.FloatField(max_length=10,default=0)
    def __str__(self):
        return f"{self.nomCl} {self.prenomCl}"

class fournisseur(models.Model):
    # codeF=models.AutoField(primary_key=True)
    nomF=models.CharField(max_length=50)
    prenomF=models.CharField(max_length=50)
    adresseF=models.CharField(max_length=50)
    telephoneF=models.CharField(max_length=10)
    solde=models.FloatField(max_length=10,default=0)
    def __str__(self):
        return f"{self.nomF} {self.prenomF}"

centre_possibles=[
        (1, '1'),
        (2, '2'),
        (3, '3')
    ]
class centre(models.Model):
    # codeC=models.AutoField(primary_key=True)
    nomC=models.CharField(max_length=50)
    numeroC=models.IntegerField(choices=centre_possibles,unique=True)
    def __str__(self):
        return f"{self.numeroC}"
    
class employe(models.Model):
    # codeE=models.AutoField(primary_key=True)
    nomE=models.CharField(max_length=50)
    prenomE=models.CharField(max_length=50)
    adresseE=models.CharField(max_length=50)
    telephoneE=models.CharField(max_length=10)
    salaire_jour=models.FloatField(max_length=10)
    centre=models.ForeignKey(centre,on_delete=models.SET_NULL,null=True)
    points=models.IntegerField(default=0)
    def __str__(self):
        return f"{self.nomE} {self.prenomE}"

class absence(models.Model):
    employe=models.ForeignKey(employe,on_delete=models.CASCADE)
    dateAbsence=models.DateField()
    def __str__(self):
        return f"{self.employe} - {self.dateAbsence}"

class avanceSalaire(models.Model):
    employe=models.ForeignKey(employe,on_delete=models.CASCADE)
    montant=models.FloatField()
    dateDemande=models.DateField()
    def __str__(self):
        return f"{self.employe} - {self.dateDemande}"

class produit(models.Model):
    # codeP=models.AutoField(primary_key=True)
    nomP=models.CharField(max_length=50)
    qte=models.IntegerField()
    def __str__(self):
        return self.nomP

class venteProduit(models.Model):
    # codeVentePr=models.AutoField(primary_key=True)
    dateVente=models.DateTimeField(default=datetime.now)
    client=models.ForeignKey(client,on_delete=models.CASCADE)
    centre=models.ForeignKey(centre,on_delete=models.CASCADE)
    produitVendu=models.ForeignKey(produit,on_delete=models.CASCADE)
    qteVendu=models.IntegerField()
    prixVente=models.FloatField(max_length=10)
    montantVerse=models.FloatField(default=0)
    def __str__(self):
        return f"{self.id}-{self.client.nomCl} {self.produitVendu}"
    
class paiementCred(models.Model):
    datePaiement=models.DateTimeField(default=datetime.now)
    client=models.ForeignKey(client,on_delete=models.CASCADE)
    montantPaiement=models.FloatField(null=True,blank=True)
    def __str__(self):
        return f"{self.client.nomCl}-{self.montantPaiement}"

class matierePremiere(models.Model):
    # codeM = models.AutoField(primary_key=True)
    nomMP = models.CharField(max_length=50)
    TypeMP = models.CharField(max_length=50)
    Quantite = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.nomMP

class achat(models.Model):
    # NumAchat = models.AutoField(primary_key=True,default=1)
    dateAchat = models.DateTimeField(default=datetime.now)
    fournisseur = models.ForeignKey(fournisseur,null=True,on_delete=models.SET_NULL)
    matieresAchetes = models.ForeignKey(matierePremiere,null=True,on_delete=models.CASCADE)
    QteAchat = models.IntegerField(default=0)
    prixAchat = models.FloatField(default=0)
    montantTotal = models.FloatField(default=0)
    montantverse = models.FloatField(default=0)
    montantRestant = models.FloatField(default=0)
    def __str__(self):
        return f"{self.matieresAchetes} {self. prixAchat}"

class ReglementFournisseur(models.Model):
    dateReg = models.DateTimeField(default=datetime.now)
    Fournisseur = models.ForeignKey(fournisseur,on_delete=models.SET_NULL,null=True, blank=True,default=1)
    solde = models.FloatField(default=0)
    montantReg = models.FloatField(default=0)
    def __str__(self):
        return f"Reglement fournisseur: {self.Fournisseur}"
    
class TransfertMatierePremiere(models.Model):
    # codeTransfert=models.AutoField(primary_key=True)
    dateTransfert=models.DateTimeField(default=datetime.now)
    centre=models.ForeignKey(centre,on_delete=models.CASCADE)
    MatieresTransferes=models.ForeignKey(achat,on_delete=models.CASCADE)
    QteTrf=models.IntegerField()
    PrixUTA=models.FloatField(default=0)
    CoutTrf=models.IntegerField(default=0) 
    def __str__(self):
        return f"Transfert #{self.id}"
    
class VenteMatierePremiere(models.Model):
    # codeVenteMP = models.AutoField(primary_key=True)
    dateVente = models.DateTimeField(default=datetime.now)
    client = models.ForeignKey(client,null=True,on_delete=models.CASCADE)
    MPVendus = models.ForeignKey(matierePremiere,null=True,on_delete=models.CASCADE)
    QteVds = models.IntegerField(default=0)
    prixUT = models.FloatField(default=0)
    montantVente = models.FloatField(default=0)
    montantEncaisse = models.FloatField(default=0)
    ResteAPayer = models.FloatField(default=0)
    def __str__(self):
        return f"{self. MPVendus}"
    
class PaiementCredit(models.Model):
    DatePventeMP = models.DateTimeField(default=datetime.now)
    client= models.ForeignKey(client,null=True,on_delete=models.CASCADE)
    credit = models.FloatField(default=0)
    montantPayMP = models.FloatField(default=0)
    def __str__(self):
        return f"Paiement Credit {self.client}"

class Stock(models.Model):
    matierepremier = models.CharField(max_length=50)
    typeTransaction = models.CharField(max_length=50)
    prix = models.FloatField(default=0)
    QteTransaction = models.IntegerField()
    montantTransaction = models.FloatField(default=0)
    def __str__(self):
        return  f"{self.typeTransaction} - {self.matierepremier} "

projet/app/templates/magasin/matierePremiere/AchatMatierePremiere.html
<!DOCTYPE html>
<html>
  <head>
    <title>Achat Matiere Premiere</title>
    {{ form.media.css }}
    <style> 
       .form-sp { 
           margin-bottom : 8px;
       } 
       select {width: 10% }
       body {
        font-family: Arial, sans-serif;
        margin: 20px;
        padding: 0;
    }
    h1 {
        margin-bottom: 20px;
    }
    form {
        margin-bottom: 20px;
    }
    label {
        margin-right: 10px;
    }
    button {
        padding: 5px 10px;
        background-color: #007bff;
        color: #fff;
        border: none;
        cursor: pointer;
    }
    button:hover {
        background-color: #0056b3;
    }
    input[type="submit"] {
      margin: 5px;
      padding: 5px 10px;
      background-color: #007bff;
      color: #fff;
      border: none;
      cursor: pointer;
      }
    </style>
  </head>
  <body>
    <h3>Acheter Matiere Premiere :</h3>
    <div>
    <form method="POST">
      {% csrf_token %}  
      <div class="form-sp"> 
        <label>Date Achat </label> 
        {{ form.dateAchat }} 
    </div>
    <div class="form-sp"> 
        <label>Fournisseur </label> 
        {{ form.fournisseur }} 
    </div>
    <div class="form-sp"> 
        <label>Matiere Premiere</label> 
        {{ form.matieresAchetes }} 
    </div> 
    <div class="form-sp"> 
        <label>Quantite achetée</label> 
        {{ form.QteAchat }} 
    </div> 
    <div class="form-sp"> 
        <label>prix Achat</label> 
        {{ form.prixAchat }} 
    </div>
    <div class="form-sp"> 
        <label>Montant Total</label> 
        {{ form.montantTotal }} 
    </div>	 
    <div class="form-sp"> 
        <label>Montant versé</label> 
        {{ form.montantverse }} 
    </div>
    <div class="form-sp"> 
        <label>Montant Restant</label> 
        {{ form.montantRestant }} 
    </div>	
      <input type="submit" value="Confirmer Achat" />
    </form>
    </div> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js">

    </script>
      {{ form.media.js }}
    <p>{{message}}</p>
    
    </script>
    <div style="position: fixed; top: 85px; left: 18.5%; text-align: center; padding: 8px;">
      <a href="{% url 'addF' %}" style="text-decoration: none;">
          <button style="padding: 4px 10px;">Ajouter Fournisseur</button>
      </a>
  </div>
    <a href="{% url 'liste_matierePremieres' %}">
      <button>Liste Matière Premières</button>
    </a>
    <a href="{% url 'liste_AchatmatierePremieres' %}">
      <button>Journal achat Matière Premières</button>
    </a> 
  </br>
</br>
    <a href="magasin">
      <button>retourner</button>
    </a>
    <script src="" async defer></script>
  </body>
</html>

projet/app/templates/magasin/matierePremiere/AjusterStock.html
<h3>Ajuster Stock</h3>
<form method="POST">
  {% csrf_token %} {{ form.as_p}}
  <a href=" {% url 'EtatStock' %}" id="annuler">
    <button>Annuler</button>
  </a>
  <input type="submit" value="Modifier" />
</form>

<script>
  document
    .getElementById("annuler")
    .addEventListener("click", function (event) {
      event.preventDefault();
      window.location.href = "{% url 'EtatStock' %}";
    });
</script>

projet/app/templates/magasin/matierePremiere/EditAchatMatierePremiere.html
<h3>Modifier Achat Matière Premières</h3>
<form method="POST">
  {% csrf_token %} {{ form.as_p}}
  <a href=" {% url 'liste_AchatmatierePremieres' %}" id="annuler">
    <button>Annuler</button>
  </a>
  <input type="submit" value="Modifier" />
</form>
{{form.media}}
<script>
  document
    .getElementById("annuler")
    .addEventListener("click", function (event) {
      event.preventDefault();
      window.location.href ="{% url 'liste_AchatmatierePremieres' %}";
    });
</script>

projet/app/templates/magasin/matierePremiere/EditVenteMatierePremiere.html
<h3>Modifier Achat Matière Premières</h3>
<form method="POST">
  {% csrf_token %} {{ form.as_p}}
  <a href=" {% url 'liste_VentematierePremieres' %}" id="annuler">
    <button>Annuler</button>
  </a>
  <input type="submit" value="Modifier" />
</form>
{{form.media}}
<script>
  document
    .getElementById("annuler")
    .addEventListener("click", function (event) {
      event.preventDefault();
      window.location.href ="{% url 'liste_VentematierePremieres' %}";
    });
</script>

projet/app/templates/magasin/matierePremiere/JournalAchatMP.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
      body {
        font-family: Arial, sans-serif;
        margin: 20px;
        padding: 0;
    }
    h1 {
        margin-bottom: 20px;
    }
    form {
        margin-bottom: 20px;
    }
    label {
        margin-right: 10px;
    }
    button {
        padding: 5px 10px;
        background-color: #007bff;
        color: #fff;
        border: none;
        cursor: pointer;
    }
    button:hover {
        background-color: #0056b3;
    }
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }
    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }
    th {
        background-color: #f2f2f2;
    }
    a.edit-link {
      display: inline-block;
      padding: 8px 16px;
      text-decoration: none;
      background-color: #007bff;
      color: #fff;
      border: none;
      border-radius: 4px;
      transition: background-color 0.3s ease;
  }
  
  a.edit-link:hover {
      background-color: #0056b3;
  }
  a.delete-link {
    display: inline-block;
    padding: 8px 16px;
    text-decoration: none;
    background-color: #dc3545;
    color: #fff;
    border: none;
    border-radius: 4px;
    transition: background-color 0.3s ease;
}

  a.delete-link:hover {
    background-color: #c82333;
}
    </style>
    <title>Journal Achat Matiere Premiere</title>
</head>
<body>
    <h1>Journal achat matiere Premières</h1>
    <form method="GET" action="{% url 'liste_AchatmatierePremieres' %}" class="form-inline">
      <div class="form-group">
          <label for="dateAchat">Entrez la dateAchat:</label>
          <input type="text" name="dateAchat" id="filter-dateAchat" class="form-control" placeholder="yyyy-mm-dd hh:mm:ss" />
      </div> 
      <div class="form-group">
          <label for="fournisseur">Entrez le nom fournisseur:</label>
          <input type="text" name="fournisseur" id="filter-fournisseur" class="form-control" />
      </div> 
      <div class="form-group">
          <label for="MP">Entrez le nom de la matière première:</label>
          <input type="text" name="MP" id="filter-MP" class="form-control" />
      </div> 
      <div class="form-group">
          <label for="QteAchat">Entrez la Quantité:</label>
          <input type="text" name="QteAchat" id="filter-QteAchat" class="form-control" />
      </div>
      <div class="form-group">
          <label for="prixAchat">Entrez le prix:</label>
          <input type="text" name="prixAchat" id="filter-prixAchat" class="form-control" />
      </div>
      <button type="submit" class="btn btn-outline-info">Filter</button>
  </form>
    <br />

    <form method="GET" action="{% url 'liste_AchatmatierePremieres' %}">
      <label for="sort_by">Trier par:</label>
      <select name="sort_by" id="sort_by">
          <option value="dateAchat">Date Achat</option>
          <option value="fournisseur">Fournisseur</option>
          <option value="matieresAchetes">Matiere Premiere</option>
          <option value="QteAchat">Quantite achetée</option>
          <option value="montantTotal">Montant Total</option>
          <option value="montantverse">Montant versé</option>
      </select>
      <button type="submit">Trier</button>
  </form>

    {% if achatmatierePremieres %}
    <table border="1px">
      <thead>
        <tr>
          <th></th>
          <th>Date Achat</th>
          <th>Fournisseur</th>
          <th>Matiere Premiere</th>
          <th>Quantite achetée</th>
          <th>prix Achat</th>
          <th>Montant Total</th>
          <th>Montant versé</th>
        </tr>
      </thead>
      
      {% for mpA in achatmatierePremieres %}
      <tbody>
        <tr>
          <td>{{mpA.id}}</td>
          <td>{{mpA.dateAchat}}</td>
          <td>{{mpA.fournisseur}}</td>
          <td>{{mpA.matieresAchetes}}</td>
          <td>{{mpA.QteAchat}}</td>
          <td>{{mpA.prixAchat}}</td>
          <td>{{mpA.montantTotal}}</td>
          <td>{{mpA.montantverse}}</td>
          <td>
            <a href="{% url 'editAchatMP' mpA.id %}" class="edit-link">Modifier</a>
          </td>
          <td>
            <a href="{% url 'deleteAchatMP' mpA.id %}" class="delete-link">Supprimer</a>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
    <p>Montant Total Achat ={{sommeachat}}</p></p>
    {% else %}
    <p>Aucune Matière Première a afficher</p>
    {% endif %}    
    <a href="{% url 'ReglerAchatMP' %}"><button>Reglements Fournisseurs</button></a>
    <br />
    <br />

    <a href="magasin">
      <button>retourner</button>
    </a>
</body>
</html>

projet/app/templates/magasin/matierePremiere/PaiementCredit.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {{ form.media.css }}
        <style>
        .form-sp { 
            margin-bottom : 8px;
        } 
        select {width: 10% } 
        <style>
          select {width: 10% }
           body {
               font-family: Arial, sans-serif;
               margin: 20px;
               padding: 0;
           }
           h1 {
               margin-bottom: 20px;
           }
           form {
               margin-bottom: 20px;
           }
           label {
               margin-right: 10px;
           }
           button {
               margin : 5px;
               padding: 5px 10px;
               background-color: #007bff;
               color: #fff;
               border: none;
               cursor: pointer;
           }
           button:hover {
               background-color: #0056b3;
           }
           input[type="submit"] {
           margin: 5px;
           padding: 5px 10px;
           background-color: #007bff;
           color: #fff;
           border: none;
           cursor: pointer;
           }
       </style>
        <title>Paiement Credit</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    <body>
    <div>
      <form method="POST">
        {% csrf_token %} {{ form.as_p}}
        <script>
          $(document).ready(function () {
              $('.client-dropdown').change(function () {
                  var clientId = $(this).val();

                  $.ajax({
                      url: '/get_credit/', 
                      method: 'GET',
                      data: { 'client_id': clientId },
                      success: function (data) {
                          $('#id_credit').val(data.credit);
                      }
                  });
              });
          });
      </script>
        <input type="submit" value="Confirmer Paiement" />
      </form>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js">
    </script>
    {{ form.media.js }}
    <p>{{message}}</p>
    <a href="{% url 'liste_VentematierePremieres' %}">
      <button>Journal vente Matière Premières</button>
    </a> 
    <br />

    <a href="magasin">
      <button>retourner</button>
    </a>
  
</body>
</html> 

projet/app/templates/magasin/matierePremiere/ReglementAchat.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {{ form.media.css }}
        <style>
        .form-sp { 
            margin-bottom : 8px;
        } 
        select {width: 10% } 
        <style>
          select {width: 10% }
           body {
               font-family: Arial, sans-serif;
               margin: 20px;
               padding: 0;
           }
           h1 {
               margin-bottom: 20px;
           }
           form {
               margin-bottom: 20px;
           }
           label {
               margin-right: 10px;
           }
           button {
               margin : 5px;
               padding: 5px 10px;
               background-color: #007bff;
               color: #fff;
               border: none;
               cursor: pointer;
           }
           button:hover {
               background-color: #0056b3;
           }
           input[type="submit"] {
           margin: 5px;
           padding: 5px 10px;
           background-color: #007bff;
           color: #fff;
           border: none;
           cursor: pointer;
           }
       </style>
        </style>
        <title>Reglement Fournisseur</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    <body>
    <h3>Regler Fournisseur:</h3>
    <div>
      <form method="POST">
        {% csrf_token %} {{ form.as_p}}
        <script>
          $(document).ready(function () {
              // Add an event listener to the Fournisseur dropdown
              $('.fournisseur-dropdown').change(function () {
                  var fournisseurId = $(this).val();

                  // Fetch solde via AJAX or directly from the rendered data

                  $.ajax({
                      url: '/get_solde/',  // Replace with your actual URL to fetch solde
                      method: 'GET',
                      data: { 'fournisseur_id': fournisseurId },
                      success: function (data) {
                          // Update the "solde" field
                          $('#id_solde').val(data.solde);
                      }
                  });
              });
          });
      </script>
        <input type="submit" value="Confirmer Reglement" />
      </form>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js">
    </script>
    {{ form.media.js }}
    <p>{{message}}</p>

    <a href="{% url 'liste_AchatmatierePremieres' %}">
      <button>Journal achat Matière Premières</button>
    </a> 
  
</body>
</html> 

projet/app/templates/magasin/matierePremiere/TransfertMatierePremiere.html
<head>
  <title>Transfert Matiere Premiere</title>
  {{ form.media.css }}
  <style> 
     .form-sp { 
         margin-bottom : 8px;
     } 
     select {width: 10% }
      body {
        font-family: Arial, sans-serif;
        margin: 20px;
        padding: 0;
    }
    h1 {
        margin-bottom: 20px;
    }
    form {
        margin-bottom: 20px;
    }
    label {
        margin-right: 10px;
    }
    button {
        padding: 5px 10px;
        background-color: #007bff;
        color: #fff;
        border: none;
        cursor: pointer;
    }
    button:hover {
        background-color: #0056b3;
    }
    input[type="submit"] {
      margin: 5px;
      padding: 5px 10px;
      background-color: #007bff;
      color: #fff;
      border: none;
      cursor: pointer;
      }
  </style>
</head>
<h3>Transferer Matiere Premiere</h3>
<form method="POST">
    {% csrf_token %}  

    {{form.as_p}}
    <input type="submit" value="Confirmer Transfert" />
  </form>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js">
  </script>
    {{ form.media.js }}
    <p>{{message}}</p>
 <a href="{% url 'liste_TransfertmatierePremieres' %}">
    <button>Journal Transfert Matière Premières</button>
  </a> 
  <a href="magasin">
    <button>retourner</button>
  </a>